### ISSUE TITLE
AWS Batch resource deployment UX improvements

### ISSUE THREAD

**Issue by araghukas** [AgnostiqHQ/covalent-awsbatch-plugin#91]
See [here](https://www.notion.so/agnostiq-public/OS-Resource-Deployment-UX-Review-bf7dbe6a025c40208b204c82739aca05?pvs=4#d105725fe21f49998d39ccb9c3408889) for notes.

<img src="https://drive.google.com/uc?id=1badz0sTgIA2OkhGW3FzFI6d4OfEMXNjC">

- The following infra defaults are not used for resource creation:
```
vcpus
memory
num_gpus
retry_attempts
time_limit
poll_freq
container_image_uri
```

- Empty defaults in the help menu should be replaced with
```python
credentials: str = str(Path.home() / ".aws/credentials")
profile: str = "default"
...
vpc_id: str = "default"
subnet_id: str = "default"
```

- The parameter named `vcpu` here is named `vcpus` in GCP Batch. Neither should be an infra parameter, else names should be resolved.

- The following names conflict across the plugin and infra defaults

ExecutorPluginDefault | ExecutorInfraDefaults
-- | --
region | aws_region
s3_bucket_name | aws_s3_bucket
batch_queue | aws_batch_queue

```[tasklist]
### Tasks
- [ ] Review infra defaults NOT used for resource creation
- [ ] Populate currently-empty infra defaults for help menu
- [ ] Change `vcpu` parameter to `vcpus` (or change in GCP Batch)
- [ ] Resolve plugin vs. infra parameter name conflicts
```
